### ISSUE TITLE
[BUG] Types no longer match implementation

### ISSUE THREAD

**Issue by acdoussan** [npm/read#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

current implementation is an async function, but the typescript types do not match this, ref: https://www.npmjs.com/package/@types/read

### Expected Behavior

Type matches implementation

### Steps To Reproduce

1. type to use in typescript
2. notice types don't match implementation

### Environment

- npm:
- Node:
- OS:
- platform:

**Comment by lukekarrys** [comment]
the new promise interface as released in `v2.0.0` as a breaking change, so the types will need to be updated at https://github.com/DefinitelyTyped/DefinitelyTyped
